/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const ActionObject: core.serialization.ObjectSchema<serializers.ActionObject.Raw, PartnerstackApi.ActionObject> =
    core.serialization
        .object({})
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).Action));

export declare namespace ActionObject {
    interface Raw extends serializers.BaseObject.Raw, serializers.Action.Raw {}
}
