/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const ArchiveActionResponse: core.serialization.ObjectSchema<
    serializers.ArchiveActionResponse.Raw,
    PartnerStackApi.ArchiveActionResponse
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace ArchiveActionResponse {
    interface Raw extends serializers.BaseResponse.Raw {}
}
