/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const ListAllActionsResponse: core.serialization.ObjectSchema<
    serializers.ListAllActionsResponse.Raw,
    PartnerStackApi.ListAllActionsResponse
> = core.serialization
    .object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).ListAllActionsData),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace ListAllActionsResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.ListAllActionsData.Raw;
    }
}
