/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const ListAllActionsData: core.serialization.ObjectSchema<
    serializers.ListAllActionsData.Raw,
    PartnerStackApi.ListAllActionsData
> = core.serialization.object({
    hasMore: core.serialization.property("has_more", core.serialization.boolean().optional()),
    items: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).ActionObject))
        .optional(),
    total: core.serialization.number().optional(),
});

export declare namespace ListAllActionsData {
    interface Raw {
        has_more?: boolean | null;
        items?: serializers.ActionObject.Raw[] | null;
        total?: number | null;
    }
}
