/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const RecordActionResponse: core.serialization.ObjectSchema<
    serializers.RecordActionResponse.Raw,
    PartnerStackApi.RecordActionResponse
> = core.serialization
    .object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).RecordActionResponseData),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace RecordActionResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.RecordActionResponseData.Raw;
    }
}
