/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const RecordActionResponseData: core.serialization.ObjectSchema<
    serializers.RecordActionResponseData.Raw,
    PartnerstackApi.RecordActionResponseData
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).RecordActionRequestBody));

export declare namespace RecordActionResponseData {
    interface Raw extends serializers.BaseObject.Raw, serializers.RecordActionRequestBody.Raw {}
}
