/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

export interface AssignPartnershipResponse extends PartnerStackApi.BaseResponse {}
