/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

export type CreateDealRequestBody =
    | PartnerStackApi.CreateDealRequestBody.GroupKey
    | PartnerStackApi.CreateDealRequestBody.PartnerKey
    | PartnerStackApi.CreateDealRequestBody._Unknown;

export declare namespace CreateDealRequestBody {
    interface GroupKey extends PartnerStackApi.GroupKey, _Utils {
        type: "group_key";
    }

    interface PartnerKey extends PartnerStackApi.PartnerKey, _Utils {
        type: "partner_key";
    }

    interface _Unknown extends _Utils {
        type: void;
    }

    interface _Utils {
        _visit: <_Result>(visitor: PartnerStackApi.CreateDealRequestBody._Visitor<_Result>) => _Result;
    }

    interface _Visitor<_Result> {
        groupKey: (value: PartnerStackApi.GroupKey) => _Result;
        partnerKey: (value: PartnerStackApi.PartnerKey) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const CreateDealRequestBody = {
    groupKey: (value: PartnerStackApi.GroupKey): PartnerStackApi.CreateDealRequestBody.GroupKey => {
        return {
            ...value,
            type: "group_key",
            _visit: function <_Result>(
                this: PartnerStackApi.CreateDealRequestBody.GroupKey,
                visitor: PartnerStackApi.CreateDealRequestBody._Visitor<_Result>
            ) {
                return PartnerStackApi.CreateDealRequestBody._visit(this, visitor);
            },
        };
    },

    partnerKey: (value: PartnerStackApi.PartnerKey): PartnerStackApi.CreateDealRequestBody.PartnerKey => {
        return {
            ...value,
            type: "partner_key",
            _visit: function <_Result>(
                this: PartnerStackApi.CreateDealRequestBody.PartnerKey,
                visitor: PartnerStackApi.CreateDealRequestBody._Visitor<_Result>
            ) {
                return PartnerStackApi.CreateDealRequestBody._visit(this, visitor);
            },
        };
    },

    _unknown: (value: { type: string }): PartnerStackApi.CreateDealRequestBody._Unknown => {
        return {
            ...(value as any),
            _visit: function <_Result>(
                this: PartnerStackApi.CreateDealRequestBody._Unknown,
                visitor: PartnerStackApi.CreateDealRequestBody._Visitor<_Result>
            ) {
                return PartnerStackApi.CreateDealRequestBody._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: PartnerStackApi.CreateDealRequestBody,
        visitor: PartnerStackApi.CreateDealRequestBody._Visitor<_Result>
    ): _Result => {
        switch (value.type) {
            case "group_key":
                return visitor.groupKey(value);
            case "partner_key":
                return visitor.partnerKey(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
