/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Source of the deal, defaults to 'partner' if not specified
 */
export type DealSource = "partner" | "vendor";

export const DealSource = {
    Partner: "partner",
    Vendor: "vendor",
} as const;
