/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

export interface DealFileResponse extends PartnerStackApi.BaseResponse {
    data: PartnerStackApi.DealFileData;
}
