/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

/**
 * **Deals** allow your partners to submit accounts they are working to your sales team to avoid channel conflicts and earn commissions for closed accounts. Typically the Deals experience is handled through a CRM integration like Salesforce. However you may opt to use the Deals API to have PartnerStack interact with a custom data warehouse rather than directly with your CRM.
 */
export interface DealObject {
    /** Name of the account */
    accountName?: string;
    /** Deal amount in **cents** */
    amount?: number;
    /** Expected close date of deal as YYYY-MM-DD */
    closeDate?: string;
    /** First name of the account's contact */
    contactFirstName?: string;
    /** Last name of the account's contact */
    contactLastName?: string;
    /** Reference that can be used in place of the key. */
    externalKey?: string;
    fields?: PartnerStackApi.FieldData[];
    /** The unique key of the group in which this deals's partner is in */
    groupKey?: string;
    /** Reason for which the deal was lost. */
    lostReason?: string;
    moldKey?: string;
    /** The unique key of the partner who owns this deal */
    partnerKey?: string;
    /** Source of the deal, either 'partner' or 'vendor', defaults to 'partner' if not specified */
    source?: PartnerStackApi.DealSource;
    /** Current stage of this deal. Must appear in Deals Stage list found in group settings. */
    stage?: string;
    /** Standard fields that are present on all database objects. */
    team?: PartnerStackApi.Team;
    teamMember?: PartnerStackApi.TeamMember;
}
