/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerstackApi } from "@fern-api/partnerstack";

export interface DealFilesData {
    dealFiles?: PartnerstackApi.DealFile[];
}
