/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerstackApi } from "@fern-api/partnerstack";

/**
 * **FormTemplates** are configurable on many of our supported objects. These forms act as a way to collect additional information on object create
 */
export interface FormTemplate {
    /** A description for users to better understand the form */
    description?: string;
    fields?: PartnerstackApi.FieldData[];
    groups?: PartnerstackApi.Group[];
    /** The presented name of this form */
    name?: string;
    /** A title to display to users when they fill out the form */
    title?: string;
    /** The type of object within PartnerStack that this form translates to */
    type?: string;
}
