/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * **Groups** are a way to segment partners within PartnerStack to selectively distribute access to things such as Campaigns, Marketing Assets, and Rewards
 */
export interface Group {
    /** Whether or not this group is still active */
    archived?: boolean;
    /** Whether this is the default Group for partners to join */
    default?: boolean;
    /** The name of this Group as presented to partners */
    name?: string;
    /** The slugified version of this groups name to be added to routes */
    slug?: string;
}
