/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerstackApi } from "@fern-api/partnerstack";

export interface GroupKey extends PartnerstackApi.BaseKey {
    /** The unique key of the group in which this deals's prospective partner is. Required if 'source' is specified as 'vendor' */
    groupKey: string;
}
