/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

export interface ListAllDealsResponse extends PartnerStackApi.BaseResponse {
    data: PartnerStackApi.ListAllDealsData;
}
