/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerstackApi } from "@fern-api/partnerstack";

export interface PartnerKey extends PartnerstackApi.BaseKey {
    /** The unique key of the partner who owns this deal. Required if 'source' is specified as 'partner'. */
    partnerKey: string;
}
