/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

export interface Team extends PartnerStackApi.BaseObject {
    /** The name of the partner team */
    name?: string;
}
