/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerstackApi } from "@fern-api/partnerstack";

export interface TeamMember extends PartnerstackApi.BaseObject {
    /** Email of the partner team member */
    email?: string;
    /** First name of the partner team member */
    firstName?: string;
    /** Last name of the partner team member */
    lastName?: string;
}
