/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const AssignPartnershipResponse: core.serialization.ObjectSchema<
    serializers.AssignPartnershipResponse.Raw,
    PartnerStackApi.AssignPartnershipResponse
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace AssignPartnershipResponse {
    interface Raw extends serializers.BaseResponse.Raw {}
}
