/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const CreateDealRequestBody: core.serialization.Schema<
    serializers.CreateDealRequestBody.Raw,
    PartnerStackApi.CreateDealRequestBody
> = core.serialization.lazyObject(async () => (await import("../../..")).BaseKey);

export declare namespace CreateDealRequestBody {
    type Raw = serializers.BaseKey.Raw;
}
