/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const CustomerResponseData: core.serialization.ObjectSchema<
    serializers.CustomerResponseData.Raw,
    PartnerStackApi.CustomerResponseData
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).CustomerObject));

export declare namespace CustomerResponseData {
    interface Raw extends serializers.BaseObject.Raw, serializers.CustomerObject.Raw {}
}
