/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const CustomerResponse: core.serialization.ObjectSchema<
    serializers.CustomerResponse.Raw,
    PartnerStackApi.CustomerResponse
> = core.serialization
    .object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).CustomerResponseData),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace CustomerResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.CustomerResponseData.Raw;
    }
}
