/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealDetails: core.serialization.ObjectSchema<serializers.DealDetails.Raw, PartnerstackApi.DealDetails> =
    core.serialization
        .object({
            data: core.serialization.lazyObject(async () => (await import("../../..")).DealDetailsData),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace DealDetails {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.DealDetailsData.Raw;
    }
}
