/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealFile: core.serialization.ObjectSchema<serializers.DealFile.Raw, PartnerstackApi.DealFile> =
    core.serialization.object({
        fieldKey: core.serialization.property("field_key", core.serialization.string().optional()),
        key: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace DealFile {
    interface Raw {
        field_key?: string | null;
        key?: string | null;
        name?: string | null;
    }
}
