/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealResponseData: core.serialization.ObjectSchema<
    serializers.DealResponseData.Raw,
    PartnerstackApi.DealResponseData
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).DealObject));

export declare namespace DealResponseData {
    interface Raw extends serializers.BaseObject.Raw, serializers.DealObject.Raw {}
}
