/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealFileResponse: core.serialization.ObjectSchema<
    serializers.DealFileResponse.Raw,
    PartnerStackApi.DealFileResponse
> = core.serialization
    .object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).DealFileData),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace DealFileResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.DealFileData.Raw;
    }
}
