/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealFileData: core.serialization.ObjectSchema<serializers.DealFileData.Raw, PartnerstackApi.DealFileData> =
    core.serialization.object({
        url: core.serialization.string().optional(),
    });

export declare namespace DealFileData {
    interface Raw {
        url?: string | null;
    }
}
