/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealDetailsData: core.serialization.ObjectSchema<
    serializers.DealDetailsData.Raw,
    PartnerStackApi.DealDetailsData
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).DealDetails));

export declare namespace DealDetailsData {
    interface Raw extends serializers.BaseObject.Raw, serializers.DealDetails.Raw {}
}
