/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealResponse: core.serialization.ObjectSchema<serializers.DealResponse.Raw, PartnerstackApi.DealResponse> =
    core.serialization
        .object({
            data: core.serialization.lazyObject(async () => (await import("../../..")).DealResponseData),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace DealResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.DealResponseData.Raw;
    }
}
