/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const DealFilesData: core.serialization.ObjectSchema<
    serializers.DealFilesData.Raw,
    PartnerstackApi.DealFilesData
> = core.serialization.object({
    dealFiles: core.serialization.property(
        "deal_files",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).DealFile))
            .optional()
    ),
});

export declare namespace DealFilesData {
    interface Raw {
        deal_files?: serializers.DealFile.Raw[] | null;
    }
}
