/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const Deal: core.serialization.ObjectSchema<serializers.Deal.Raw, PartnerStackApi.Deal> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).DealObject));

export declare namespace Deal {
    interface Raw extends serializers.BaseObject.Raw, serializers.DealObject.Raw {}
}
