/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const FormTemplateData: core.serialization.ObjectSchema<
    serializers.FormTemplateData.Raw,
    PartnerstackApi.FormTemplateData
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).FormTemplate));

export declare namespace FormTemplateData {
    interface Raw extends serializers.BaseObject.Raw, serializers.FormTemplate.Raw {}
}
