/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const FormTemplate: core.serialization.ObjectSchema<serializers.FormTemplate.Raw, PartnerStackApi.FormTemplate> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        fields: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).FieldData))
            .optional(),
        groups: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).Group))
            .optional(),
        name: core.serialization.string().optional(),
        title: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
    });

export declare namespace FormTemplate {
    interface Raw {
        description?: string | null;
        fields?: serializers.FieldData.Raw[] | null;
        groups?: serializers.Group.Raw[] | null;
        name?: string | null;
        title?: string | null;
        type?: string | null;
    }
}
