/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const FormTemplateResponse: core.serialization.ObjectSchema<
    serializers.FormTemplateResponse.Raw,
    PartnerstackApi.FormTemplateResponse
> = core.serialization
    .object({
        data: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).FormTemplateData)
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace FormTemplateResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.FormTemplateData.Raw[];
    }
}
