/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const GroupKey: core.serialization.ObjectSchema<serializers.GroupKey.Raw, PartnerstackApi.GroupKey> =
    core.serialization
        .object({
            groupKey: core.serialization.property("group_key", core.serialization.string()),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseKey));

export declare namespace GroupKey {
    interface Raw extends serializers.BaseKey.Raw {
        group_key: string;
    }
}
