/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const Group: core.serialization.ObjectSchema<serializers.Group.Raw, PartnerStackApi.Group> =
    core.serialization.object({
        archived: core.serialization.boolean().optional(),
        default: core.serialization.boolean().optional(),
        name: core.serialization.string().optional(),
        slug: core.serialization.string().optional(),
    });

export declare namespace Group {
    interface Raw {
        archived?: boolean | null;
        default?: boolean | null;
        name?: string | null;
        slug?: string | null;
    }
}
