/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const ListAllDealsResponse: core.serialization.ObjectSchema<
    serializers.ListAllDealsResponse.Raw,
    PartnerStackApi.ListAllDealsResponse
> = core.serialization
    .object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).ListAllDealsData),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace ListAllDealsResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        data: serializers.ListAllDealsData.Raw;
    }
}
