/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const PartnerKey: core.serialization.ObjectSchema<serializers.PartnerKey.Raw, PartnerStackApi.PartnerKey> =
    core.serialization
        .object({
            partnerKey: core.serialization.property("partner_key", core.serialization.string()),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseKey));

export declare namespace PartnerKey {
    interface Raw extends serializers.BaseKey.Raw {
        partner_key: string;
    }
}
