/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const TeamMember: core.serialization.ObjectSchema<serializers.TeamMember.Raw, PartnerStackApi.TeamMember> =
    core.serialization
        .object({
            email: core.serialization.string().optional(),
            firstName: core.serialization.property("first_name", core.serialization.string().optional()),
            lastName: core.serialization.property("last_name", core.serialization.string().optional()),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseObject));

export declare namespace TeamMember {
    interface Raw extends serializers.BaseObject.Raw {
        email?: string | null;
        first_name?: string | null;
        last_name?: string | null;
    }
}
