/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../../core";

export const ConvertDealToCustomerRequest: core.serialization.Schema<
    serializers.ConvertDealToCustomerRequest.Raw,
    PartnerstackApi.ConvertDealToCustomerRequest
> = core.serialization.object({
    customerKey: core.serialization.property("customer_key", core.serialization.string().optional()),
    email: core.serialization.string(),
});

export declare namespace ConvertDealToCustomerRequest {
    interface Raw {
        customer_key?: string | null;
        email: string;
    }
}
