/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerstackVendorApi } from "@fern-api/partnerstack";

export type BadRequestError = PartnerstackVendorApi.PartnershipResponse;
