/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class PartnerStackApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, PartnerStackApiTimeoutError.prototype);
    }
}
