/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PartnerstackVendorApi } from "@fern-api/partnerstack";
import * as core from "../../../core";

export const Id: core.schemas.Schema<serializers.Id.Raw, PartnerstackVendorApi.Id> = core.schemas.string();

export declare namespace Id {
  type Raw = string;
}
