/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListAllActionsRequest {
    /**
     * Applies a minimum epoch timestamp (ms) filter to the response `created_at`.
     */
    minCreated?: number;
    /**
     * Applies a maximum epoch timestamp (ms) filter to the response `created_at`.
     */
    maxCreated?: number;
    /**
     * Applies a minimum epoch timestamp (ms) filter to the response `updated_at`.
     */
    minUpdated?: number;
    /**
     * Applies a maximum epoch timestamp (ms) filter to the response `updated_at`.
     */
    maxUpdated?: number;
    /**
     * Partnership key in which the results are filtered by.
     */
    partnershipKey?: string;
    /**
     * Will filter for actions with the specified name.
     */
    actionType?: string;
    /**
     * The field in which the results are ordered by. A `-` prefix denotes that the results are in descending order.
     */
    orderBy?: string;
    /**
     * A limit on the number of items to be returned. Limits can range between 1 and 250, and the default is 10.
     */
    limit?: number;
    /**
     * A cursor for use in pagination, `starting_after` takes in an item key and the subsequent call will return the following items in the list. This is mutually exclusive with `ending_before`.
     */
    startingAfter?: string;
    /**
     * A cursor for use in pagination, `ending_before` takes in an item key and the subsequent call will return the prior items in the list. This is mutually exclusive with `starting_after`.
     */
    endingBefore?: string;
}
