/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PartnerstackVendorApi } from "@fern-api/partnerstack";
import * as core from "../../../core";

export const Response: core.schemas.Schema<
  serializers.deal.assignPartnership.Response.Raw,
  PartnerstackVendorApi.PartnershipResponse
> = core.schemas.lazyObject(async () => (await import("../..")).PartnershipResponse);

export declare namespace Response {
  type Raw = serializers.PartnershipResponse.Raw;
}
