/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { PartnerStackApi } from "@fern-api/partnerstack";
import * as core from "../../../../../core";

export const RecordActionRequest: core.serialization.Schema<
    serializers.RecordActionRequest.Raw,
    PartnerStackApi.RecordActionRequest
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../../..")).BaseRequestBody));

export declare namespace RecordActionRequest {
    interface Raw extends serializers.BaseRequestBody.Raw {}
}
