/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PartnerStackApi } from "@fern-api/partnerstack";

export interface UpdateDealRequest {
    accountName?: string;
    amount?: number;
    closeDate?: string;
    contactFirstName?: string;
    contactLastName?: string;
    externalKey?: string;
    fields?: PartnerStackApi.FieldData[];
    groupKey?: string;
    lostReason?: string;
    moldKey?: string;
    partnerKey?: string;
    source?: PartnerStackApi.DealSource;
    stage?: string;
    team?: PartnerStackApi.Team;
    teamMember?: PartnerStackApi.TeamMember;
}
