/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PartnerstackVendorApi } from "@fern-api/partnerstack";
import * as core from "../../../core";

export const BadRequestError: core.schemas.Schema<
  serializers.BadRequestError.Raw,
  PartnerstackVendorApi.BadRequestError
> = core.schemas.lazyObject(async () => (await import("../..")).PartnershipResponse);

export declare namespace BadRequestError {
  type Raw = serializers.PartnershipResponse.Raw;
}
