/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PartnerstackVendorApi } from "@fern-api/partnerstack";
import * as core from "../../../core";

export const UnauthorizedError: core.schemas.Schema<
  serializers.UnauthorizedError.Raw,
  PartnerstackVendorApi.UnauthorizedError
> = core.schemas.lazyObject(async () => (await import("../..")).PartnershipResponse);

export declare namespace UnauthorizedError {
  type Raw = serializers.PartnershipResponse.Raw;
}
