/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PartnerstackVendorApi } from "@fern-api/partnerstack";
import * as core from "../../../core";

export const DealId: core.schemas.Schema<serializers.DealId.Raw, PartnerstackVendorApi.DealId> = core.schemas.string();

export declare namespace DealId {
  type Raw = string;
}
