/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PartnerstackVendorApi } from "@fern-api/partnerstack";
import * as core from "../../../core";

export const PartnershipResponse: core.schemas.ObjectSchema<
  serializers.PartnershipResponse.Raw,
  PartnerstackVendorApi.PartnershipResponse
> = core.schemas.object({
  message: core.schemas.string(),
  status: core.schemas.number(),
});

export declare namespace PartnershipResponse {
  interface Raw {
    message: string;
    status: number;
  }
}
