/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Standard fields that are present on all database objects.
 */
export interface BaseObject {
    /** Immutable Unix timestamp in milliseconds taken at time of creation */
    createdAt?: number;
    /** A unique identifier used to reference the object */
    key?: string;
    /** Unix timestamp in milliseconds taken at time of last update */
    updatedAt?: number;
}
