/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Base schema representation of a customer
 */
export interface Company {
    /** Unique key of this company */
    key?: string;
    /** The name of this company */
    name?: string;
}
