/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Base schema representation of a customer
 */
export interface Customer {
    /** Unique key of this customer */
    key?: string;
    subIds?: string[];
}
