/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * **FieldData** combines attributes about a field with its submitted value on target object
 */
export interface FieldData {
    /** API name of this field to be used on create / update / serialization. Created at time of field creation but can be edited */
    apiName?: string;
    /** Name that can be used for external systems */
    externalType?: string;
    /** Key of field that is presented */
    fieldKey?: string;
    /** The help text that is provided for this field */
    helpText?: string;
    /** Whether or not this field is displayed when filling out its attached form */
    hidden?: boolean;
    /** Internal name of this field. Created by PartnerStack at time of field creation. Used when referencing field in created objects. Cannot be edited. */
    internalName?: string;
    /** Name of field that is presented */
    name?: string;
    /** The text of the placeholder that is provided for this field */
    placeholderText?: string;
    /** The position that this field will be displayed in relation to others on the same form (index starts at 0) */
    position?: number;
    /** Whether or not this field will be required when filling out its attached form */
    required?: boolean;
    /** The type of field that will be presented (input, picklist, number ect.) */
    type?: string;
}
