/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether to record an action under a partnership or customer
 */
export type TargetType = "partnership" | "customer";

export const TargetType = {
    Partnership: "partnership",
    Customer: "customer",
} as const;
