/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ActionsClient } from "./api/resources/actions/client/Client";
import { Client as DealsClient } from "./api/resources/deals/client/Client";

export declare namespace PartnerStackApiClient {
    interface Options {
        environment?: environments.PartnerStackApiEnvironment | string;
        credentials?: core.Supplier<core.BasicAuth>;
    }
}

export class PartnerStackApiClient {
    constructor(private readonly options: PartnerStackApiClient.Options) {}

    #actions: ActionsClient | undefined;

    public get actions(): ActionsClient {
        return (this.#actions ??= new ActionsClient(this.options));
    }

    #deals: DealsClient | undefined;

    public get deals(): DealsClient {
        return (this.#deals ??= new DealsClient(this.options));
    }
}
