/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as DealClient } from "./resources/deal/client/Client";

export declare namespace PartnerstackVendorApiClient {
  interface Options {
    environment?: environments.PartnerstackVendorApiEnvironment | string;
    credentials?: core.Supplier<core.BasicAuth>;
  }
}

export class PartnerstackVendorApiClient {
  constructor(private readonly options: PartnerstackVendorApiClient.Options) {}

  #deal: DealClient | undefined;

  public get deal(): DealClient {
    return (this.#deal ??= new DealClient(this.options));
  }
}
