/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PartnerstackApiEnvironment = {
    Production: "https://api.partnerstack.com/api",
} as const;

export type PartnerstackApiEnvironment = typeof PartnerstackApiEnvironment.Production;
