/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PartnerStackApiEnvironment = {
    Production: "https://api.partnerstack.com/api",
} as const;

export type PartnerStackApiEnvironment = typeof PartnerStackApiEnvironment.Production;
