/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PartnerstackVendorApiEnvironment = {
  Production: "https://api.partnerstack.com/api/v2/partnerships",
} as const;

export type PartnerstackVendorApiEnvironment = typeof PartnerstackVendorApiEnvironment.Production;
