/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PartnerstackApi } from "@fern-api/partnerstack";
import * as core from "../../../../core";

export const Company: core.serialization.ObjectSchema<serializers.Company.Raw, PartnerstackApi.Company> =
    core.serialization.object({
        key: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace Company {
    interface Raw {
        key?: string | null;
        name?: string | null;
    }
}
